describe('Fabrique test2', () => {
   beforeEach(() => {
       cy.viewport(1280, 720)
       cy.visit('https://fabrique:fabrique@finance.dev.fabrique.studio/accounts/login/')
       cy.get("[type='email']").type('admin@admin.ad')
       cy.get("[type='password']").type('admin')
       cy.get("[type='submit']").click()
   })
   it('ТС2 Добавление платежа - доход', {
    "defaultCommandTimeout": 5000
}, () => {
       cy.get('.pageLayout__actions > :nth-child(1) > .button').click()
       cy.xpath("(//div[@class='checkbox__content'])[1]").click()
       cy.xpath("(//textarea[@type='textarea'])[1]").type('описание')
       cy.xpath("(//div[@class='checkbox__content'])[4]").click()
       cy.xpath("(//input[@type='text'])[1]").type('10000')
       cy.xpath("(//input[@type='text'])[2]").type('1000')
       cy.xpath("(//div[contains(text(),'Не оплачен')])[1]").click()
       cy.xpath("(//input[@class='date__input'])[1]").click()
       cy.xpath("(//button[normalize-space()='20'])[1]").click()
       cy.xpath("(//input[@class='date__input'])[2]").click()
       cy.xpath("(//button[normalize-space()='7'])[1]").click()
       cy.xpath("(//div[@class='select__caret multiselect__select'])[1]").click().type("шла{enter}")
       cy.xpath("(//textarea[@type='textarea'])[2]").type("И сосала сушку")
       cy.xpath("(//div[@class='select__caret multiselect__select'])[2]").click().type("выс{enter}")
       cy.xpath("(//div[@class='select__caret multiselect__select'])[3]").click().type('a1{enter}')
       cy.xpath("(//div[@class='select__caret multiselect__select'])[4]").click().type("космос{enter}")
       cy.xpath("(//div[@class='select__caret multiselect__select'])[5]").click().type('123123{enter}')
       cy.xpath("(//div[@class='select__caret multiselect__select'])[6]").click().type('ыыы{enter}')
       cy.xpath("(//div[@class='select__caret multiselect__select'])[7]").click().type('бархатные{enter}')
       cy.xpath("(//button[@type='submit'])[1]").click()
   })
   it('ТС3 Добавление платежа - расход', {
    "defaultCommandTimeout": 5000
}, () => {
       cy.get('.pageLayout__actions > :nth-child(1) > .button').click()
       cy.xpath("(//div[@class='checkbox__content'])[2]").click()
       cy.xpath("(//textarea[@type='textarea'])[1]").type('описание')
       cy.xpath("(//div[@class='checkbox__content'])[4]").click()
       cy.xpath("(//input[@type='text'])[1]").type('10000')
       cy.xpath("(//div[contains(text(),'Не оплачен')])[1]").click()
       cy.xpath("(//input[@class='date__input'])[1]").click()
       cy.xpath("(//button[normalize-space()='20'])[1]").click()
       cy.xpath("(//input[@class='date__input'])[2]").click()
       cy.xpath("(//button[normalize-space()='7'])[1]").click()
       cy.xpath("(//div[@class='select__caret multiselect__select'])[1]").click().type("уме{enter}")
       cy.xpath("(//textarea[@type='textarea'])[2]").type("ньшающийся")
       cy.xpath("(//div[@class='select__caret multiselect__select'])[2]").click().type('a1{enter}')
       cy.xpath("(//div[@class='select__caret multiselect__select'])[3]").click().type("космос{enter}")
       cy.xpath("(//div[@class='icon icon--size-xs'])[9]").click().type('бархатные{enter}')
       cy.xpath("(//button[@type='submit'])[1]").click()
   })
})